openapi: 3.0.1
info:
  title: Vocode
  description: A plugin that allows the user to create GPT-powered automated phone calls.
  version: "v1"
servers:
  - url: http://localhost:5003
paths:
  /call:
    post:
      operationId: call
      summary: Creates an outbound call
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createOutboundCall"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/callResponse"

components:
  schemas:
    callResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Success/fail boolean for the outbound call.
    createOutboundCall:
      type: object
      properties:
        recipient_number:
          required: true
          type: string
          description: The recipient's phone number.
        gpt_prompt:
          required: true
          type: string
          description: GPT prompt for the AI agent making the phone call; in other words, instructions for GPT.
        initial_message:
          required: true
          type: string
          description: A hard-coded initial message for GPT to begin the conversation with.
